version: "1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    image: looleeluu/devops-for-programmers-project-74
    environment:
      DATABASE_NAME: ${DATABASE_NAME:-postgres}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      DATABASE_HOST: ${DATABASE_HOST:-db}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
