services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make dev
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"

  caddy:
    image: caddy:2.9
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    depends_on:
      - app
