name: push

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Make tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: make test
        run: |
          make test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devops-for-programmers-project-74:latest
